--- #YAML:1.0
name:               Acme-EyeDrops
version:            1.41
abstract:           Visual Programming in Perl
license:            perl
distribution_type:  module
installdirs:        site
requires:
  perl: 5.005
